name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: laytan/setup-odin@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          llvm-version: 17

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm

      - run: npm install --no-frozen-lockfile
      - run: npm run build-test
