name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup LLVM and Odin
        run: ./setup_odin.sh

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm

      - run: pnpm install --no-frozen-lockfile
      - run: pnpm run build-test
